name: CI/CD Maven + SonarQube

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      sonarqube:
        image: sonarqube:lts
        ports:
          - 9000:9000

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Maven
        run: mvn clean verify -B -f MyWebApp/pom.xml

      - name: Wait for SonarQube
        run: |
          echo "Waiting for SonarQube to start..."
          until curl -s http://localhost:9000/api/system/status | grep -q '"status":"UP"'; do
            sleep 5
          done

      - name: Run SonarScanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=my-Java-web-app \
            -Dsonar.sources=MyWebApp/src \
            -Dsonar.java.binaries=MyWebApp/target/classes \
            -Dsonar.host.url=http://localhost:9000
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
